language: cpp
compiler:
  - clang
  - gcc
sudo: false
addons:
  apt:
    packages:
    - freeglut3-dev
    - libglfw-dev
    - libxml2-dev
    - zlib1g-dev
script:
  - ./ci/cpplint.sh
notifications:
  email: false
